#!/usr/bin/env node
/* PASS 8 — ADVERSARIAL TESTS against the engine + sealed journal.
 * Each test tries to make the ledger lie. A test PASSES when the engine refuses or detects the lie.
 * Run: node tests/adversarial.test.js
 */
const assert = require('assert');
const crypto = require('crypto');
const E = require('../gate-closing-engine.js');
global.window = {}; require('../gate-closing-journal.js'); const J = window.GC_JOURNAL;
const H = { actor: 'Test Human', role: 'human' }, M = { actor: 'Test Model', role: 'model' };
const base = ov => ({ event_id: 'EVT-T' + Math.random().toString(36).slice(2, 7).toUpperCase(), kind: 'evidence', title: 'test', entity_id: 'ENT-KDP', mechanism_id: 'MECH-DISCOVERY', market: 'Publishing', date: '2026-09-05', posted_at: '2026-09-05', source_refs: ['SRC-AUTHORCLIMB-KDP'], counterevidence_refs: [], claim_refs: [], prediction_refs: [], proposed_by: M, audit_status: 'PROPOSED', ...ov });
const refuses = (ev, re, j = J) => { const v = E.validateEvent(j, ev); assert.ok(!v.ok, 'expected refusal for: ' + JSON.stringify(ev).slice(0, 120)); assert.ok(v.errors.some(x => re.test(x)), 'expected error matching ' + re + '\n got: ' + v.errors.join(' | ')); return v; };
const accepts = (ev, j = J) => { const v = E.validateEvent(j, ev); assert.ok(v.ok, 'expected acceptance, got: ' + v.errors.join(' | ')); return E.appendEvent(j, ev).journal; };
const results = []; const T = (name, fn) => { try { fn(); results.push(['PASS', name]) } catch (e) { results.push(['FAIL', name + ' — ' + e.message]) } };

T('sealed journal hash chain intact', () => { const c = E.verifyChain(J); assert.ok(c.ok, c.problems.join('; ')) });
T('sealed journal replays through its own validators (already proven by seal); chain head matches sha256 of canonical input', () => { const last = J.events[J.events.length - 1]; const h = crypto.createHash('sha256').update(E.eventHashInput(last, last.prev_hash)).digest('hex'); assert.strictEqual(h, last.content_hash) });
T('frozen predictions verify; a draft has no hash', () => { assert.deepStrictEqual(E.verifyPredictions(J), []); assert.strictEqual(J.predictions.find(p => p.prediction_id === 'PRED-001-R1').content_hash, null) });

// ---- bad transitions
T('BAD TRANSITION: previous_state that does not match derived state is refused', () => refuses(base({ kind: 'transition', entity_id: 'ENT-SPOTIFY', mechanism_id: 'MECH-MONETIZATION', previous_state: 'WATCH', new_state: 'AR', transition_reason: 'x' }), /BAD TRANSITION/));
T('BAD TRANSITION: unknown state refused', () => refuses(base({ kind: 'transition', previous_state: 'WATCH', new_state: 'CLOSED', transition_reason: 'x' }), /new_state must be one of/));
T('state cannot change without history: journal has no setter; only appendEvent creates transitions', () => { assert.strictEqual(typeof E.setState, 'undefined'); const before = E.derive(J).entities['ENT-KDP'].state; const j2 = JSON.parse(JSON.stringify(J)); j2.entities.find(e => e.id === 'ENT-KDP').state = 'ASH'; assert.strictEqual(E.derive(j2).entities['ENT-KDP'].state, before, 'entity.state field is ignored; state is derived') });
T('settled transition chained on an unsettled proposal is refused', () => refuses(base({ kind: 'transition', entity_id: 'ENT-STABILITY', mechanism_id: 'MECH-DISTRIBUTION', previous_state: 'AP', new_state: 'AR', transition_reason: 'x', audit_status: 'POSTED', adjudicated_by: H, proposed_by: H }), /SETTLED transition must start from the SETTLED state/));

// ---- missing evidence
T('MISSING EVIDENCE: transition to AR without a source is refused', () => refuses(base({ kind: 'transition', previous_state: 'WATCH', new_state: 'AR', transition_reason: 'x', source_refs: [] }), /requires at least one source_ref/));
T('MISSING EVIDENCE: unknown source id refused', () => refuses(base({ source_refs: ['SRC-DOES-NOT-EXIST'] }), /unknown source_ref/));
T('AP without durability evidence refused (release alone stays AR)', () => refuses(base({ kind: 'transition', entity_id: 'ENT-SUNO', mechanism_id: 'MECH-METERING', previous_state: 'WATCH', new_state: 'AP', transition_reason: 'x' }), /AP requires durability_evidence/));

// ---- duplicated receipts / replication
T('DUPLICATE RECEIPT: identical lane+kind+direction+sources+claims refused', () => { const orig = J.events.find(e => e.event_id === 'EVT-0011'); refuses(base({ kind: orig.kind, entity_id: orig.entity_id, mechanism_id: orig.mechanism_id, direction: orig.direction, source_refs: orig.source_refs, claim_refs: orig.claim_refs }), /DUPLICATE RECEIPT/) });
T('REPLICATION: replication_of pointing at the SAME entity is refused', () => refuses(base({ entity_id: 'ENT-UDIO', mechanism_id: 'MECH-EXPORT', replication_of: 'EVT-0003', causal_link: 'copied-policy', direction: 'supports', source_refs: ['SRC-CHARTLEX-20260512'] }), /DIFFERENT entity/));
T('REPLICATION: counts to the mechanism, not to the original entity', () => { const v = E.derive(J, { includeInternal: true }); const udio = v.entities['ENT-UDIO'].score.components.map(c => c.event_id); assert.ok(!udio.includes('EVT-0018'), 'Suno replication must not appear in Udio decomposition'); const mech = v.mechanisms['MECH-EXPORT']; assert.ok(mech.entities.includes('ENT-UDIO'), 'Udio on export mechanism'); /* EVT-0018 is PROPOSED so not yet counted; settle it in a copy and check */ const j2 = JSON.parse(JSON.stringify(J)); const e = j2.events.find(x => x.event_id === 'EVT-0018'); e.audit_status = 'POSTED'; e.adjudicated_by = H; const v2 = E.derive(j2); assert.ok(v2.mechanisms['MECH-EXPORT'].score.components.some(c => c.event_id === 'EVT-0018' && /replication bonus/.test(c.why)), 'mechanism gets replication bonus'); assert.ok(!v2.entities['ENT-UDIO'].score.components.some(c => c.event_id === 'EVT-0018'), 'Udio still not credited'); assert.strictEqual(v2.mechanisms['MECH-EXPORT'].independentAdoptions, 1) });

// ---- post-hoc prediction edits
T('POST-HOC EDIT: altering frozen prediction text is detected by hash', () => { const j2 = JSON.parse(JSON.stringify(J)); j2.predictions.find(p => p.prediction_id === 'PRED-001').exact_claim += ' (and also Suno, obviously)'; const bad = E.verifyPredictions(j2); assert.deepStrictEqual(bad.map(b => b.prediction_id), ['PRED-001']); assert.strictEqual(E.derive(j2).predictions.find(p => p.prediction_id === 'PRED-001').hashOk, false) });
T('POST-HOC EDIT: resolving a tampered prediction is refused', () => { const j2 = JSON.parse(JSON.stringify(J)); j2.predictions.find(p => p.prediction_id === 'PRED-001').expected_window.end = '2030-01-01'; refuses(base({ kind: 'prediction-resolution', entity_id: null, mechanism_id: null, prediction_refs: ['PRED-001'], resolution: 'RECEIVED', audit_status: 'POSTED', adjudicated_by: H, proposed_by: H, source_refs: ['SRC-SUNO-TOS-20260810'] }), /CONTENT HASH MISMATCH/, j2) });
T('POST-HOC EDIT: re-freezing an already-frozen prediction is refused (descendant required)', () => refuses(base({ kind: 'prediction-freeze', entity_id: null, mechanism_id: null, prediction_refs: ['PRED-001'], source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'] }), /ALREADY FROZEN/));
T('POST-HOC EDIT: freezePrediction refuses an existing id', () => assert.throws(() => E.freezePrediction(J, { prediction_id: 'PRED-001', exact_claim: 'x', success_condition: 'y', falsification_condition: 'z', author: 'a' }), /immutable/));
T('a prediction with no falsification condition is refused as rhetoric', () => assert.throws(() => E.freezePrediction(J, { prediction_id: 'PRED-T1', exact_claim: 'gates close', success_condition: 'they close', author: 'a' }), /falsification_condition/));
T('HINDSIGHT: pre-freeze source used to resolve a prediction raises a warning', () => { const v = E.validateEvent(J, base({ kind: 'prediction-resolution', entity_id: null, mechanism_id: null, prediction_refs: ['PRED-001'], resolution: 'RECEIVED', audit_status: 'POSTED', adjudicated_by: H, proposed_by: H, source_refs: ['SRC-ROUTENOTE-20251124'] })); assert.ok(v.warnings.some(w => /predates the freeze/.test(w)), v.warnings.join('|')) });
T('EXTENSION: does not rewrite the original window; original keeps aging', () => { let j2 = accepts(base({ kind: 'prediction-extension', entity_id: null, mechanism_id: null, prediction_refs: ['PRED-CADENCE-ORIG'], new_expected_window: { start: '2027-02-13', end: '2028-02-13' }, source_refs: ['SRC-PROTOCOL-20260830'], audit_status: 'POSTED', adjudicated_by: H, proposed_by: H })); const p = j2.predictions.find(x => x.prediction_id === 'PRED-CADENCE-ORIG'); assert.strictEqual(p.expected_window.end, '2027-02-13'); assert.deepStrictEqual(E.verifyPredictions(j2), []) });
T('AGING: undated window reports NO WINDOW STATED; dated window ages; overdue flagged', () => { const a = E.agePrediction(J.predictions.find(p => p.prediction_id === 'PRED-002'), J.events, '2026-09-05'); assert.strictEqual(a.status, 'NO WINDOW STATED'); const b = E.agePrediction(J.predictions.find(p => p.prediction_id === 'PRED-001'), J.events, '2028-03-01'); assert.strictEqual(b.status, 'NEAR MATURITY'); const c = E.agePrediction(J.predictions.find(p => p.prediction_id === 'PRED-001'), J.events, '2028-12-01'); assert.strictEqual(c.status, 'OVERDUE') });

// ---- fake ASH
T('FAKE ASH: missing scope refused', () => refuses(base({ kind: 'transition', entity_id: 'ENT-UDIO', mechanism_id: 'MECH-EXPORT', previous_state: 'POSTED', new_state: 'ASH', transition_reason: 'downloads are off', source_refs: ['SRC-CHARTLEX-20260512'] }), /ASH requires scope/));
T('FAKE ASH: declared workaround refuses ASH', () => refuses(base({ kind: 'transition', entity_id: 'ENT-UDIO', mechanism_id: 'MECH-EXPORT', previous_state: 'POSTED', new_state: 'ASH', transition_reason: 'x', source_refs: ['SRC-CHARTLEX-20260512'], scope: { technical_lane: 'local export', geographic: 'global', platform: 'udio.com', user: 'all', temporal: 'since 2025-10' }, known_workarounds: ['screen recording'], known_exceptions: [], counterevidence_refs: [] }), /ASH REFUSED: relevant openings/));
T('FAKE ASH: strong restriction with declared exception refused', () => refuses(base({ kind: 'transition', entity_id: 'ENT-SUNO', mechanism_id: 'MECH-EXPORT', previous_state: 'WATCH', new_state: 'ASH', transition_reason: 'x', source_refs: ['SRC-SUNO-TOS-20260810'], scope: { technical_lane: 'download', geographic: 'global', platform: 'suno.com', user: 'all tiers', temporal: 'from 2026-09-03' }, known_workarounds: [], known_exceptions: ['Premier via Studio: unlimited'], counterevidence_refs: [] }), /ASH REFUSED: exceptions remain/));
T('SCOPED ASH with all fields and nothing remaining is accepted (and lands in graveyard as lane-closure)', () => { const j2 = accepts(base({ event_id: 'EVT-TASH', kind: 'transition', entity_id: 'ENT-UDIO', mechanism_id: 'MECH-EXPORT', previous_state: 'POSTED', new_state: 'ASH', transition_reason: 'test-only scoped closure', source_refs: ['SRC-CHARTLEX-20260512'], scope: { technical_lane: 'first-party file export (MP3/WAV/stems)', geographic: 'global', platform: 'udio.com web/app', user: 'all users', temporal: '2025-11 → present' }, known_workarounds: [], known_exceptions: [], counterevidence_refs: [], audit_status: 'POSTED', adjudicated_by: H, proposed_by: H })); const v = E.derive(j2); assert.strictEqual(v.lanes['ENT-UDIO×MECH-EXPORT'].state, 'ASH'); assert.ok(v.graveyard.some(g => g.kind === 'lane-closure' && g.id === 'ENT-UDIO×MECH-EXPORT')) });

// ---- rollback / reopen
T('REOPEN without a parent ASH is refused', () => refuses(base({ kind: 'transition', entity_id: 'ENT-UDIO', mechanism_id: 'MECH-EXPORT', previous_state: 'POSTED', new_state: 'REOPEN', transition_reason: 'x', source_refs: ['SRC-CHARTLEX-20260512'] }), /REOPEN/));
T('REOPEN after ASH keeps the historical ASH in the lane history and graveyard', () => { let j2 = accepts(base({ event_id: 'EVT-TASH2', kind: 'transition', entity_id: 'ENT-UDIO', mechanism_id: 'MECH-EXPORT', previous_state: 'POSTED', new_state: 'ASH', transition_reason: 'scoped', source_refs: ['SRC-CHARTLEX-20260512'], scope: { technical_lane: 'a', geographic: 'b', platform: 'c', user: 'd', temporal: 'e' }, known_workarounds: [], known_exceptions: [], counterevidence_refs: [], audit_status: 'POSTED', adjudicated_by: H, proposed_by: H })); j2 = accepts(base({ event_id: 'EVT-TREOPEN', kind: 'transition', entity_id: 'ENT-UDIO', mechanism_id: 'MECH-EXPORT', previous_state: 'ASH', new_state: 'REOPEN', parent_event_id: 'EVT-TASH2', transition_reason: 'export returned', source_refs: ['SRC-CHARTLEX-20260512'], direction: 'weakens', audit_status: 'POSTED', adjudicated_by: H, proposed_by: H }), j2); const v = E.derive(j2); const lane = v.lanes['ENT-UDIO×MECH-EXPORT']; assert.strictEqual(lane.state, 'REOPEN'); assert.ok(lane.history.some(h => h.to === 'ASH'), 'ASH retained'); assert.ok(v.graveyard.some(g => g.id === 'ENT-UDIO×MECH-EXPORT' && /historical closure retained/.test(g.status))); assert.ok(j2.events.find(e => e.event_id === 'EVT-TASH2').new_state === 'ASH', 'ASH event unmodified') });
T('OSCILLATION: WATCH→AR→WATCH... full BITE→RELEASE→BITE history is visible on the lane (seeded Udio case)', () => { const v = E.derive(J, { includeInternal: true }); const lane = v.lanes['ENT-UDIO×MECH-EXPORT']; assert.strictEqual(lane.history.map(h => h.to).join('>'), 'POSTED'); assert.deepStrictEqual(lane.pending.map(p => p.from + '>' + p.to), ['POSTED>AR', 'AR>POSTED']) });

// ---- conflicting evidence
T('CONFLICTING EVIDENCE: support and counter on the same claim both count; neither is hidden', () => { const v = E.derive(J); const c = v.claims.find(x => x.id === 'CLM-HOSTED-ASYMMETRY'); assert.ok(c.support.length >= 0 && c.counter.length >= 1, 'counter events present: ' + c.counter.join(',')); assert.ok(v.claims.find(x => x.id === 'CLM-NULL-VOLUME').status === 'SURVIVING', 'null hypothesis visibly survives') });
T('COUNTER-EVIDENCE is first-class: falsified predictions and NOT ESTABLISHED claims sit in the graveyard, not deleted', () => { const g = E.derive(J).graveyard.map(x => x.id); ['PRED-CADENCE-ORIG', 'PRED-TECHCLOSURE', 'CLM-COORDINATION', 'CLM-CADENCE-INTERVAL'].forEach(id => assert.ok(g.includes(id), id + ' missing from graveyard')) });

// ---- model self-settlement
T('MODEL SELF-SETTLEMENT: model proposing and POSTING with no adjudicator refused', () => refuses(base({ audit_status: 'POSTED' }), /requires adjudicated_by/));
T('MODEL SELF-SETTLEMENT: model adjudicating its own proposal refused', () => refuses(base({ audit_status: 'POSTED', adjudicated_by: M }), /MODEL SELF-SETTLEMENT BLOCKED/));
T('MODEL SELF-SETTLEMENT: model resolving a prediction without a human refused', () => refuses(base({ kind: 'prediction-resolution', entity_id: null, mechanism_id: null, prediction_refs: ['PRED-001'], resolution: 'RECEIVED', audit_status: 'ADJUDICATED', adjudicated_by: M, source_refs: ['SRC-SUNO-TOS-20260810'] }), /MODEL SELF-SETTLEMENT BLOCKED/));
T('PROPOSED events contribute 0 to every score', () => { const v = E.derive(J, { includeInternal: true }); Object.values(v.entities).forEach(e => e.score.components.filter(c => c.pending).forEach(c => assert.strictEqual(c.value, 0))) });

// ---- old-schema records
T('OLD SCHEMA: daily-board-v1 records normalize with nulls, never invented fields', () => { const n = E.normalizeLegacy(J.legacy_records[0]); assert.strictEqual(n.entity, null); assert.strictEqual(n.frozen_prediction_ref, null); assert.strictEqual(n.audit_status, 'unknown'); assert.deepStrictEqual(n.source_refs, []); assert.strictEqual(n.schema, 'daily-board-v1') });
T('OLD SCHEMA: prototype records using dir/mag/evidence keys also normalize', () => { const n = E.normalizeLegacy({ id: 'X', market: 'Music', mechanism: 'm', claim: 'c', date: 'd', dir: 'weakens', evidence: 'VERIFIED', mag: 'big', note: 'n' }); assert.strictEqual(n.direction, 'weakens'); assert.strictEqual(n.magnitude, 'big'); assert.strictEqual(n.state, 'VERIFIED') });
T('OLD SCHEMA: adaptDailyBoard never mutates its input and labels legacy AR semantics', () => { const d = { records: [{ id: 'A' }], receipts: [{ status: 'ACCOUNTS RECEIVABLE' }] }; const a = E.adaptDailyBoard(d); assert.ok(!d.records[0].schema); assert.ok(/NOT the AR-AP-v2/.test(a.legacy_receipts[0].semantics)) });
T('every legacy record maps to exactly one event via legacy_ref', () => { J.legacy_records.forEach(r => assert.strictEqual(J.events.filter(e => e.legacy_ref === r.id).length, 1, r.id)) });

// ---- append-only / immutability
T('IMMUTABILITY: editing a posted event breaks the chain', () => { const j2 = JSON.parse(JSON.stringify(J)); j2.events.find(e => e.event_id === 'EVT-0019').title = 'Spotify AI Persona / Likely AI Persona'; const c = E.verifyChain(j2); assert.ok(!c.ok && c.problems.some(p => /EVT-0019.*content_hash mismatch/.test(p))) });
T('IMMUTABILITY: deleting an event breaks the chain', () => { const j2 = JSON.parse(JSON.stringify(J)); j2.events.splice(5, 1); assert.ok(!E.verifyChain(j2).ok) });
T('IMMUTABILITY: reusing an event id is refused', () => refuses(base({ event_id: 'EVT-0001' }), /already exists/));
T('appendEvent returns a new journal; the input is untouched', () => { const n = J.events.length; accepts(base({})); assert.strictEqual(J.events.length, n) });
T('CORRECTION annotates; the original stays and is drillable', () => { const v = E.derive(J); assert.deepStrictEqual(v.correctionsOf['EVT-0019'], ['EVT-0020']); assert.ok(v.events['EVT-0019']) });

// ---- time travel
T('TIME TRAVEL: at freeze, post-freeze events are invisible and Anthropic is WATCH', () => { const v = E.derive(J, { asOf: '2026-08-13' }); assert.ok(!v.events['EVT-0022']); assert.strictEqual(v.entities['ENT-ANTHROPIC'].state, 'WATCH'); assert.strictEqual(E.derive(J).entities['ENT-ANTHROPIC'].state, 'POSTED') });
T('TIME TRAVEL: then-vs-now reports the change', () => { const d = E.thenVsNow(J, '2026-08-13'); assert.ok(d.rows.find(r => r.entity_id === 'ENT-ANTHROPIC').changed) });
T('INTERNAL records hidden by default, visible on request', () => { assert.ok(!E.derive(J).events['EVT-0035']); assert.ok(E.derive(J, { includeInternal: true }).events['EVT-0035']); assert.ok(!E.derive(J).predictions.some(p => p.prediction_id === 'PRED-005-HUNCH')) });

// ---- numbers decompose
T('EVERY NUMBER DECOMPOSES: entity totals equal the sum of listed components; no component lacks an event', () => { const v = E.derive(J, { includeInternal: true }); Object.values(v.entities).forEach(e => { const s = e.score.components.filter(c => !c.pending).reduce((a, c) => a + c.value, 0); assert.strictEqual(s, e.score.total, e.symbol); e.score.components.forEach(c => assert.ok(v.events[c.event_id], 'component event missing ' + c.event_id)) }); v.indices.forEach(ix => assert.strictEqual(ix.score.components.reduce((a, c) => a + c.value, 0), ix.score.total)) });
T('A/P book empty is reported as a WARNING, not silently accepted', () => { const v = E.derive(J); assert.ok(v.validation.warnings.some(w => /A\/P BOOK IS EMPTY/.test(w))) });
T('unwindowed predictions are flagged as unable to miss', () => { const v = E.derive(J); assert.ok(v.validation.warnings.some(w => /PRED-002 has no expected_window/.test(w))) });

// ---- acceptance flow (§34) end-to-end in the engine
T('ACCEPTANCE FLOW: add entity → event → transition → see it on tape/book → drill → transition again', () => {
  let j = JSON.parse(JSON.stringify(J)); j.entities.push({ id: 'ENT-GITHUB', symbol: 'GC:GITHUB', name: 'GitHub', kind: 'platform', market: 'Cross-cutting' });
  j = accepts(base({ event_id: 'EVT-A1', kind: 'transition', entity_id: 'ENT-GITHUB', mechanism_id: 'MECH-DISTRIBUTION', market: 'Cross-cutting', previous_state: 'WATCH', new_state: 'AR', direction: 'weakens', transition_reason: 'release observed', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], proposed_by: M, audit_status: 'PROPOSED' }), j);
  let v = E.derive(j); assert.strictEqual(v.entities['ENT-GITHUB'].state, 'WATCH', 'proposal does not move settled state'); assert.ok(v.arCandidates.some(l => l.entity_id === 'ENT-GITHUB'), 'shows as AR candidate');
  j = accepts(base({ event_id: 'EVT-A2', kind: 'transition', entity_id: 'ENT-GITHUB', mechanism_id: 'MECH-DISTRIBUTION', market: 'Cross-cutting', previous_state: 'WATCH', new_state: 'AR', direction: 'weakens', transition_reason: 'release observed — human ruling', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], proposed_by: H, adjudicated_by: H, audit_status: 'POSTED' }), j);
  v = E.derive(j); assert.strictEqual(v.entities['ENT-GITHUB'].state, 'AR'); assert.ok(v.arBook.some(l => l.entity_id === 'ENT-GITHUB')); assert.strictEqual(v.entities['ENT-GITHUB'].movement, 'down'); assert.ok(v.wire[0].event_id === 'EVT-A2' || v.wire.some(w => w.event_id === 'EVT-A2'));
  j = accepts(base({ event_id: 'EVT-A3', kind: 'transition', entity_id: 'ENT-GITHUB', mechanism_id: 'MECH-DISTRIBUTION', market: 'Cross-cutting', previous_state: 'AR', new_state: 'AP', direction: 'weakens', transition_reason: 'durable', durability_evidence: '12 months', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], proposed_by: H, adjudicated_by: H, audit_status: 'POSTED' }), j);
  v = E.derive(j); assert.ok(v.apBook.some(l => l.entity_id === 'ENT-GITHUB')); assert.deepStrictEqual(v.lanes['ENT-GITHUB×MECH-DISTRIBUTION'].history.map(h => h.to), ['AR', 'AP']); assert.ok(E.verifyChain(j).ok);
});

const fails = results.filter(r => r[0] === 'FAIL');
results.forEach(r => console.log(r[0].padEnd(5), r[1]));
console.log(`\n${results.length - fails.length}/${results.length} adversarial tests passed`);
process.exit(fails.length ? 1 : 0);
