/* AUTHORING SOURCE for gate-closing-journal.js
 * Run:  node tools/seal-journal.js   → writes ../gate-closing-journal.js with seq / prev_hash / content_hash filled.
 * Never edit gate-closing-journal.js by hand. Append events HERE, re-seal, and commit both files.
 * Every event carries proposed_by / audit_status / adjudicated_by. Nothing authored 2026-09-05 by Claude is above PROPOSED.
 */
const ROB = { actor: 'Rob (Lokivelli) — published verdict on gate-closing-preview.html', role: 'human' };
const ROB_PROTO = { actor: 'Rob (Lokivelli) — 2026-08-30 failure/resurrection protocol', role: 'human' };
const LEGACY = { actor: 'legacy ledger drafting seat [Unknown]', role: 'model' };
const CLAUDE = { actor: 'Claude (re-entry seat, session 2026-09-05)', role: 'model' };

module.exports = {
  meta: {
    schema: 'gc-journal/1',
    semantics: 'AR-AP-v2 (Rob spec 2026-09-05): WATCH · AR=provisional opening · AP=durable opening · POSTED=adjudicated restriction evidence on ledger · ASH=scoped universal closure · REOPEN=closure reversed, history kept',
    title: 'Gate Closing Stockboard Journal', updated: '2026-09-05', freeze: '2026-08-13', protocol: '2026-08-30',
    mainPage: 'https://lokivelli316.github.io/EARLYWINE-PRESIDENTIAL-BLUEPRINT/gate-closing-build/gate-closing-preview.html',
    repoHead: '7d3a6d5 (main, 2026-09-03 13:55 -0400)',
    lineage: ['gate-closing-preview.html@main (G1)', 'GATE_EVIDENCE_TERMINAL_PROTOTYPE.html (G2a, untracked)', 'gate-closing-board-prototype.html (G2b, untracked)', 'gate-closing-data.js 2026-09-04 (G3, untracked)'],
    note: 'AP is where the thesis loses ground: a durable opening is a lane that did not close. An empty A/P book is a ledger defect, not a victory.'
  },

  mechanisms: [
    ['MECH-LICENSING', 'GC:LICENSING', 'licensing'], ['MECH-DISCLOSURE', 'GC:DISCLOSURE', 'disclosure requirements'],
    ['MECH-IDENTITY', 'GC:IDENTITY', 'identity / verification'], ['MECH-PROVENANCE', 'GC:PROVENANCE', 'provenance'],
    ['MECH-EXPORT', 'GC:EXPORT', 'export restriction'], ['MECH-VOLUME', 'GC:VOLUME', 'spam / volume controls'],
    ['MECH-DISCOVERY', 'GC:DISCOVERY', 'discovery controls'], ['MECH-MONETIZATION', 'GC:MONETIZATION', 'monetization controls'],
    ['MECH-PUBLICATION', 'GC:PUBLICATION', 'publication controls'], ['MECH-DISTRIBUTION', 'GC:DISTRIBUTION', 'distribution / platform access'],
    ['MECH-COMPLIANCE', 'GC:COMPLIANCE', 'compliance cost'], ['MECH-FILTERING', 'GC:FILTERING', 'institutional filtering'],
    ['MECH-METERING', 'GC:METERING', 'metering / billing'], ['MECH-API', 'GC:API', 'API access'], ['MECH-MODERATION', 'GC:MODERATION', 'moderation'],
    ['MECH-THROTTLING', 'GC:THROTTLING', 'throttling'], ['MECH-AUTH', 'GC:AUTH', 'authentication']
  ].map(([id, symbol, name]) => ({ id, symbol, name })),

  entities: [
    { id: 'ENT-SPOTIFY', symbol: 'GC:SPOTIFY', name: 'Spotify', kind: 'company', market: 'Music', public_ticker: 'SPOT (NYSE) — separate financial layer, not used here' },
    { id: 'ENT-UDIO', symbol: 'GC:UDIO', name: 'Udio', kind: 'company', market: 'Music' },
    { id: 'ENT-SUNO', symbol: 'GC:SUNO', name: 'Suno Inc.', kind: 'company', market: 'Music' },
    { id: 'ENT-STABILITY', symbol: 'GC:STABILITY', name: 'Stability AI (Stable Audio)', kind: 'company', market: 'Music' },
    { id: 'ENT-KDP', symbol: 'GC:KDP', name: 'Amazon KDP', kind: 'platform', market: 'Publishing', public_ticker: 'AMZN — separate financial layer, not used here' },
    { id: 'ENT-ACX', symbol: 'GC:ACX', name: 'Audible / ACX', kind: 'platform', market: 'Publishing' },
    { id: 'ENT-INGRAM', symbol: 'GC:INGRAM', name: 'IngramSpark', kind: 'platform', market: 'Publishing' },
    { id: 'ENT-ARXIV', symbol: 'GC:ARXIV', name: 'arXiv', kind: 'institution', market: 'Scholarly' },
    { id: 'ENT-ZENODO', symbol: 'GC:ZENODO', name: 'Zenodo', kind: 'institution', market: 'Scholarly' },
    { id: 'ENT-DIAMONDOA', symbol: 'GC:DIAMONDOA', name: 'Diamond Open Access journals', kind: 'market', market: 'Scholarly' },
    { id: 'ENT-EUAIACT', symbol: 'GC:EUAIACT', name: 'EU AI Act (Reg. 2024/1689)', kind: 'law', market: 'Cross-cutting' },
    { id: 'ENT-ANTHROPIC', symbol: 'GC:ANTHROPIC', name: 'Anthropic (as litigation target)', kind: 'company', market: 'Cross-cutting' },
    { id: 'ENT-MUSICFLOW', symbol: 'GC:MUSICFLOW', name: 'MusicFlow (trymusicflow.com)', kind: 'company', market: 'Music', visibility: 'internal', note: 'Entity exists only to carry the 2026-09-03 hunch freeze. Repo-only. Not for the public page.' }
  ],

  indices: [
    { id: 'IDX-MUSIC', symbol: 'GC:MUSIC', name: 'Music', market: 'Music' },
    { id: 'IDX-PUBLISHING', symbol: 'GC:PUBLISHING', name: 'Publishing', market: 'Publishing' },
    { id: 'IDX-ACADEMIC', symbol: 'GC:ACADEMIC', name: 'Scholarly', market: 'Scholarly' },
    { id: 'IDX-CROSS', symbol: 'GC:CROSS', name: 'Cross-cutting', market: 'Cross-cutting' },
    { id: 'IDX-AI', symbol: 'GC:AI', name: 'AI-generation lanes', entity_ids: ['ENT-UDIO', 'ENT-SUNO', 'ENT-STABILITY', 'ENT-ANTHROPIC', 'ENT-SPOTIFY'] }
  ],

  sources: [
    // ---- primary, fetched this seat (retrieved_by = Claude 2026-09-05)
    { id: 'SRC-SPOT-NEWSROOM-20260811', type: 'primary-corporate', title: 'Spotify Newsroom — Introducing a New Label for AI-Generated Artist Identities', url: 'https://newsroom.spotify.com/2026-08-11/ai-persona-badges-transparency/', published: '2026-08-11', retrieved: '2026-09-05', retrieved_by: 'Claude', quote: '"By default, Spotify will not include AI Personas in any editorial or algorithmic recommendations." Rollout: mid-September 2026. The phrase "Likely AI Persona" does not appear.' },
    { id: 'SRC-TC-20260811', type: 'secondary-press', title: 'TechCrunch — Spotify will label AI Persona profiles and exclude their music from recommendations', url: 'https://techcrunch.com/2026/08/11/spotify-will-label-ai-persona-profiles-and-exclude-their-music-from-recommendations/', published: '2026-08-11', retrieved: '2026-09-05', retrieved_by: 'Claude', quote: 'Determination: self-disclosure, profile review of "photorealistic AI-generated identities", audience thresholds, user reporting. No second-tier label mentioned.' },
    { id: 'SRC-SUNO-TOS-20260810', type: 'primary-corporate', title: 'Suno — An update to our downloads policy and Terms of Service', url: 'https://suno.com/blog/suno-updates-tos', published: '2026-08-10', retrieved: '2026-09-05', retrieved_by: 'Claude', quote: 'Free: up to 7 (lifetime) trial downloads. Pro: 20/month. Premier: 60/month. Studio: no download limits. "Limits apply to all downloads starting September 3, including songs created before that date." "additional downloads will be available for purchase." "Songs downloaded from Suno on paid plans remain yours to use commercially or personally." "When the new models launch, all prior models will be retired."' },
    { id: 'SRC-SUNO-HELP-13614785', type: 'primary-corporate', title: 'Suno Help — Upcoming Changes FAQ: Downloads, Models, and Terms of Service', url: 'https://help.suno.com/en/articles/13614785', published: null, retrieved: null, retrieved_by: null, note: 'Located by search 2026-09-05; not opened. Capture pending.' },
    { id: 'SRC-ARXIV-20260121', type: 'primary-institutional', title: 'arXiv blog — Attention Authors: updated endorsement policy', url: 'https://blog.arxiv.org/2026/01/21/attention-authors-updated-endorsement-policy/', published: '2026-01-21', retrieved: '2026-09-05', retrieved_by: 'Claude', quote: '"institutional email addresses are no longer a sufficient credential for determining minimum research competence or endorsement." Rationale: "unsustainable increase in the number of non-scientific submissions." All categories.' },
    { id: 'SRC-ARXIV-20251210', type: 'primary-institutional', title: 'arXiv blog — updated endorsement policy for arXiv Mathematics', url: 'https://blog.arxiv.org/2025/12/10/updated-endorsement-policy-for-arxiv-mathematics/', published: '2025-12-10', retrieved: null, retrieved_by: null, note: 'Referenced by the 2026-01-21 post; not opened this seat.' },
    { id: 'SRC-AUTHORCLIMB-KDP', type: 'secondary-blog', title: 'AuthorClimb — Amazon KDP Upload Limit: 10 Per Format, 30 Total Per Week', url: 'https://www.authorclimb.com/blog/amazon-kdp-upload-limit', published: null, retrieved: '2026-09-05', retrieved_by: 'Claude', quote: '"In late 2025, Amazon replaced the daily cap with the current weekly one: 10 new titles per book format each week." Cites KDP help G201857950.' },
    { id: 'SRC-KDP-HELP-G201857950', type: 'primary-corporate', title: 'KDP Help — Title creation limit (G201857950)', url: 'https://kdp.amazon.com/en_US/help/topic/G201857950', published: null, retrieved: null, retrieved_by: null, note: 'Cited via secondary. Primary snapshot with retrieval date still required before P-2 can carry primary weight.' },
    { id: 'SRC-ROUTENOTE-20251124', type: 'secondary-press', title: 'RouteNote — Udio stops user downloads after UMG deal', url: 'https://routenote.com/blog/udio-stops-user-downloads-after-umg-deal-heres-why/', published: '2025-11-24', retrieved: '2026-09-05', retrieved_by: 'Claude', quote: '"As a temporary measure to ease tensions, Udio briefly reopened downloads for 48 hours." Window dates not stated. "Udio users can no longer download their AI music creations at all."' },
    { id: 'SRC-CHARTLEX-20260512', type: 'secondary-blog', title: 'Chartlex — Udio-UMG Walled Garden Explained 2026', url: 'https://www.chartlex.com/blog/business/udio-umg-walled-garden-explained-2026', published: '2026-05-12', retrieved: '2026-09-05', retrieved_by: 'Claude', quote: 'Settlement/JV announced 2025-10-29; WMG Nov 2025; Merlin Jan 2026; Kobalt 2026-04-09; "As of May 2026, the platform has been in staged rollout." No local export of MP3/WAV/stems.' },
    { id: 'SRC-BILLBOARD-UDIO-48H', type: 'secondary-press', title: 'Billboard — Udio Says Users Can Download AI Songs for 48 Hours After Backlash', url: 'https://www.billboard.com/pro/udio-deal-backlash-ai-users-download-ai-songs-48-hours/', published: null, retrieved: null, retrieved_by: null, note: 'Fetch returned HTTP 402 (paywall) 2026-09-05. Headline only. Dates of the window remain [Unknown].' },
    { id: 'SRC-MARKTECHPOST-20260526', type: 'secondary-press', title: 'MarkTechPost — Stability AI Releases Stable Audio 3', url: 'https://www.marktechpost.com/2026/05/26/stability-ai-releases-stable-audio-3-a-family-of-fast-latent-diffusion-models-for-audio-generation-and-editing/', published: '2026-05-26', retrieved: null, retrieved_by: 'Claude (search result only)', note: 'Headline corroborated by multiple secondary sources; Stability primary post not captured this seat.' },
    { id: 'SRC-TC-20260829', type: 'secondary-press', title: 'TechCrunch — Sony Music, Warner sue Anthropic', url: 'https://techcrunch.com/2026/08/29/sony-music-warner-sue-anthropic-alleging-a-brazen-campaign-of-intellectual-property-theft/', published: '2026-08-29', retrieved: null, retrieved_by: 'Claude (search result only)' },
    { id: 'SRC-MBW-20260828', type: 'secondary-press', title: 'Music Business Worldwide — Sony Music Publishing and Warner Chappell sue Anthropic', url: 'https://www.musicbusinessworldwide.com/now-sony-music-publishing-and-warner-chappell-sue-anthropic-in-multi-billion-dollar-lawsuit-one-of-the-largest-and-most-blatant-ongoing-thefts-of-intellectual-property-in-history/', published: '2026-08-28', retrieved: null, retrieved_by: 'Claude (search result only)' },
    // ---- primary, cited on main, NOT re-fetched this seat
    { id: 'SRC-SPOTIFY-ROYALTY-2023', type: 'primary-corporate', title: 'Spotify for Artists — Modernizing our royalty system (1,000-stream threshold)', url: null, published: '2023-11-21', retrieved: null, note: 'Cited on main. Not re-fetched 2026-09-05. Effective April 2024.' },
    { id: 'SRC-SPOTIFY-AI-20251016', type: 'primary-corporate', title: 'Spotify Newsroom — artist-first AI products with major rights holders', url: null, published: '2025-10-16', retrieved: null, note: 'Cited on main. Not re-fetched. Date [Estimate] to the month.' },
    { id: 'SRC-KDP-AI-DISCLOSURE', type: 'primary-corporate', title: 'KDP Content Guidelines — AI-generated vs AI-assisted disclosure', url: null, published: '2023-09', retrieved: null, note: 'Cited on main. Not re-fetched.' },
    { id: 'SRC-ACX-AI-NARRATION', type: 'primary-corporate', title: 'Audible / ACX — AI narration and Voice Replica expansion', url: null, published: null, retrieved: null, note: 'Cited on main. Not re-fetched. Dates [Unknown] beyond 2025–2026.' },
    { id: 'SRC-ZENODO-POLICY', type: 'primary-institutional', title: 'Zenodo — policy on AI-generated deposits', url: null, published: '2026-04', retrieved: null, note: 'Cited on main. Not re-fetched.' },
    { id: 'SRC-EUAIACT-ART50', type: 'primary-law', title: 'Regulation (EU) 2024/1689, Art. 50 transparency obligations (applicable from 2026-08-02)', url: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj', published: '2024-07-12', retrieved: null, note: 'From knowledge; not fetched this seat.' },
    { id: 'SRC-COURT-SONY-WARNER-V-ANTHROPIC', type: 'court-filing', title: 'Sony Music Publishing & Warner Chappell v. Anthropic — complaint', url: null, published: '2026-08-28', retrieved: null, note: 'Filing itself not captured; date per press coverage. Allegations, not findings.' },
    // ---- internal / derived
    { id: 'SRC-MAIN-PREVIEW-7d3a6d5', type: 'derived', title: 'gate-closing-preview.html @ main 7d3a6d5 (records M-1…C-2, 8 receipts, verdict cards)', url: 'https://github.com/lokivelli316/EARLYWINE-PRESIDENTIAL-BLUEPRINT/blob/main/gate-closing-build/gate-closing-preview.html', published: '2026-09-03', retrieved: '2026-09-05', retrieved_by: 'Claude (git clone)', hash: 'file 46,912 bytes; commit 624adbb last touched' },
    { id: 'SRC-PROTOCOL-20260830', type: 'primary-internal', title: 'Gate Closing / AI Pincer — Prospective Failure + Resurrection Protocol', url: 'https://github.com/lokivelli316/EARLYWINE-PRESIDENTIAL-BLUEPRINT/blob/main/gate-closing-build/receipts/2026-08-30_failure-resurrection-protocol.md', published: '2026-08-30', retrieved: '2026-09-05', retrieved_by: 'Claude (git clone)' },
    { id: 'SRC-HUNCH-20260903', type: 'primary-internal', title: 'Gate Closing Receipt — Suno / MusicFlow Ownership Hunch Freeze', url: 'https://github.com/lokivelli316/EARLYWINE-PRESIDENTIAL-BLUEPRINT/blob/main/gate-closing-build/receipts/2026-09-03_suno-musicflow-ownership-hunch-freeze.md', published: '2026-09-03', retrieved: '2026-09-05', retrieved_by: 'Claude (git clone)', visibility: 'internal' },
    { id: 'SRC-STATUS-MD-20260824', type: 'derived', title: 'GATE_CLOSING_TAB_STATUS.md (2026-08-24) — IngramSpark mixed note', url: 'https://github.com/lokivelli316/EARLYWINE-PRESIDENTIAL-BLUEPRINT/blob/main/gate-closing-build/GATE_CLOSING_TAB_STATUS.md', published: '2026-08-24', retrieved: '2026-09-05', retrieved_by: 'Claude (git clone)', quote: '"IngramSpark is kept mixed because an upfront fee was removed while a backend fee was added."' },
    { id: 'SRC-DATAJS-20260904', type: 'derived', title: 'gate-closing-data.js (Daily Board, meta.updated 2026-09-04)', url: null, published: '2026-09-04', retrieved: '2026-09-05', retrieved_by: 'Claude (wire-up pack)', hash: 'sha256 f305e4078f9aa56f29c4698af18b1cfa1ce0c20bff9fc42f6d2303f41f9bb92e' },
    { id: 'SRC-G2A-TERMINAL', type: 'derived', title: 'GATE_EVIDENCE_TERMINAL_PROTOTYPE.html (untracked)', url: null, published: null, retrieved: '2026-09-05', hash: 'sha256 10cb131cb61fdfb45a3b8df72048b3b168b59a655ae06efb78732a57b02c429e' },
    { id: 'SRC-G2B-BOARD', type: 'derived', title: 'gate-closing-board-prototype.html (untracked)', url: null, published: null, retrieved: '2026-09-05', hash: 'sha256 c69743f3028a683509c8f11e589499598cbd2023f3e7f35c2e14c2fca23a04b9' }
  ],

  claims: [
    { id: 'CLM-HOSTED', text: 'Hosted / monetized convenient lanes become more governed (licensed, permissioned, metered, discoverability-controlled).', kind: 'mechanism-thesis', created_at: '2026-08-13' },
    { id: 'CLM-CROSSMKT', text: 'Similar gating primitives recur across music, publishing and scholarly deposit — convergence, not coordination.', kind: 'observation', created_at: '2026-08-13' },
    { id: 'CLM-AUTHORSHIP', text: 'Authorship / publishing gate: disclosure, volume, human-contribution and legitimacy gates predate the freeze and continue evolving.', kind: 'mechanism-thesis', created_at: '2026-08-13' },
    { id: 'CLM-TECHCLOSURE', text: 'Universal technical closure — raw generative capability becomes unavailable.', kind: 'parent', created_at: '2026-08-13' },
    { id: 'CLM-HOSTED-ASYMMETRY', text: 'Hosted-access asymmetry: raw capability can expand while convenient licensed, discoverable, monetized lanes tighten.', kind: 'descendant', parent: 'CLM-TECHCLOSURE', created_at: '2026-08-30' },
    { id: 'CLM-CADENCE-INTERVAL', text: 'Gate Closing events recur on a roughly six-month interval.', kind: 'parent', created_at: '2026-08-13' },
    { id: 'CLM-CADENCE-RECUR', text: 'Gate Closing events recur; timing may be irregular, clustered, trigger-driven or market-specific.', kind: 'descendant', parent: 'CLM-CADENCE-INTERVAL', created_at: '2026-08-30' },
    { id: 'CLM-COORDINATION', text: 'A unified secret cross-market command structure explains the observed gates.', kind: 'hypothesis', created_at: '2026-08-13' },
    { id: 'CLM-KDP-DISCOVERY', text: 'KDP discoverability becomes the next major gate.', kind: 'forward-expectation', created_at: '2026-08-13' },
    { id: 'CLM-DISCOVERYMODE', text: 'Spotify Discovery Mode suppresses non-participants.', kind: 'hypothesis', created_at: '2026-08-13' },
    { id: 'CLM-NULL-VOLUME', text: 'NULL HYPOTHESIS (adversarial, added by Claude): volume/spam floods raise moderation cost and platforms add friction — this alone explains M-1, M-5, P-2, S-1, S-2 without any Gate Closing thesis.', kind: 'null-hypothesis', created_at: '2026-09-05', proposed_by: 'Claude' }
  ],

  predictions: [
    { prediction_id: 'PRED-001', exact_claim: 'A significant AI-music company loses practical independence by roughly mid-2028.', entity: 'IDX-AI', market: 'Music', mechanism: 'MECH-LICENSING', created_at: '2026-08-13', frozen_at: '2026-08-13', prediction_horizon: '2 years', expected_window: { start: '2026-08-13', end: '2028-06-30' }, initial_confidence: null, initial_confidence_note: 'No numeric confidence was stated at freeze. Do not backfill one.', success_condition: 'Acquisition, control rights, asset transfer, insolvency/displacement, or practical exclusive-license dependency.', falsification_condition: 'No such event by the window end; or durable independence of the tracked companies through the window.', known_evidence_at_freeze: ['Udio–UMG settlement/JV (2025-10-29) and WMG deal (Nov 2025) — PRE-FREEZE; arguably already satisfies "practical exclusive-license dependency" (see PRED-001-R1 draft)'], source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], author: 'Rob (Lokivelli)', claim_refs: ['CLM-HOSTED'] },
    { prediction_id: 'PRED-001-R1', parent: 'PRED-001', exact_claim: 'DRAFT DESCENDANT (not frozen): Excluding Udio (dependency pre-dates the freeze), at least one of {Suno, Stability AI, or another AI-music generator with a material user base} enters an acquisition, controlling investment, or exclusive-license dependency with a major rights holder by 2028-06-30.', entity: 'IDX-AI', market: 'Music', mechanism: 'MECH-LICENSING', created_at: '2026-09-05', frozen_at: null, prediction_horizon: '≈22 months', expected_window: { start: '2026-09-05', end: '2028-06-30' }, initial_confidence: null, success_condition: 'Public disclosure of acquisition / controlling investment / exclusive-license dependency of a named non-Udio AI-music company.', falsification_condition: 'None of the named class by 2028-06-30.', known_evidence_at_freeze: [], source_refs: [], author: 'Claude (proposed) — requires Rob to freeze', claim_refs: ['CLM-HOSTED'] },
    { prediction_id: 'PRED-002', exact_claim: 'Where a meaningful pressure release occurs on a governed platform, at least some major governed platforms will later restore or replace that pressure with a stronger, broader, more consequential or differently positioned gate.', entity: null, market: 'Cross-cutting', mechanism: null, created_at: '2026-08-30', frozen_at: '2026-08-30', prediction_horizon: 'long range', expected_window: null, initial_confidence: null, success_condition: 'RECEIPT A (release, logged as AR) followed by RECEIPT B (stronger gate) on the same lane.', falsification_condition: 'Predicted second-stage tightening never follows a logged release; durable opposite pattern dominates.', known_evidence_at_freeze: ['Udio 48-hour window (Nov 2025) — pre-freeze; calibration only'], source_refs: ['SRC-PROTOCOL-20260830'], author: 'Rob (Lokivelli)', claim_refs: ['CLM-HOSTED', 'CLM-CADENCE-RECUR'] },
    { prediction_id: 'PRED-003', exact_claim: 'KDP discoverability becomes the next major gate.', entity: 'ENT-KDP', market: 'Publishing', mechanism: 'MECH-DISCOVERY', created_at: '2026-08-13', frozen_at: '2026-08-13', prediction_horizon: null, expected_window: null, initial_confidence: null, success_condition: 'Official or strongly evidenced KDP ranking / discovery / eligibility rule tied to AI disclosure or provenance.', falsification_condition: 'Not stated at freeze. (Cannot miss as written — see A-5 in the 2026-09-05 audit.)', known_evidence_at_freeze: [], source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], author: 'Rob (Lokivelli)', claim_refs: ['CLM-KDP-DISCOVERY'] },
    { prediction_id: 'PRED-CADENCE-ORIG', exact_claim: 'Gate Closing events recur on a roughly six-month interval.', entity: null, market: 'Cross-cutting', mechanism: null, created_at: '2026-08-13', frozen_at: '2026-08-13', prediction_horizon: '6 months', expected_window: { start: '2026-08-13', end: '2027-02-13' }, initial_confidence: null, success_condition: 'Next cluster of gate events lands ~6 months after the prior cluster.', falsification_condition: 'Interval does not hold.', known_evidence_at_freeze: [], source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], author: 'Rob (Lokivelli)', claim_refs: ['CLM-CADENCE-INTERVAL'] },
    { prediction_id: 'PRED-TECHCLOSURE', exact_claim: 'Universal technical closure: raw generative audio capability becomes unavailable outside licensed lanes.', entity: null, market: 'Music', mechanism: 'MECH-DISTRIBUTION', created_at: '2026-08-13', frozen_at: '2026-08-13', prediction_horizon: null, expected_window: null, initial_confidence: null, success_condition: 'No open-weight / self-hosted generation remains practically available.', falsification_condition: 'Open-weight or self-hosted audio generation remains available.', known_evidence_at_freeze: ['Stable Audio 3.0 open weights (2026-05-26) — pre-freeze; the parent was already dead at freeze and was adjudicated ASH on main'], source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], author: 'Rob (Lokivelli)', claim_refs: ['CLM-TECHCLOSURE'] },
    { prediction_id: 'PRED-005-HUNCH', visibility: 'internal', exact_claim: 'There may be a hidden common-ownership or control relationship worth investigating because a portability-restricting change at Suno coincided with a highly relevant MusicFlow advertisement, while MusicFlow itself appears to share pricing fingerprints with other Flow-branded AI products. No Suno-to-MusicFlow ownership bridge has been demonstrated as of the freeze date.', entity: 'ENT-MUSICFLOW', market: 'Music', mechanism: 'MECH-EXPORT', created_at: '2026-09-03', frozen_at: '2026-09-03', prediction_horizon: null, expected_window: null, initial_confidence: null, success_condition: 'Corporate filing, shared controlling officers/investors, disclosed acquisition/subsidiary/DBA, matching merchant entities, or first-party disclosure.', falsification_condition: 'Unrelated legal owner; template pricing; ad fully explained by ordinary targeting; no bridge after reasonable trace.', known_evidence_at_freeze: ['Suno limits effective 2026-09-03', 'MusicFlow $49.99/$179.99 = CinemaFlow / InteriorFlow pricing', 'gclid-tracked ad encounter'], source_refs: ['SRC-HUNCH-20260903'], author: 'Rob (Lokivelli)', claim_refs: [] }
  ],

  legacy_records: [
    // Verbatim from gate-closing-data.js (2026-09-04). Not migrated. Not edited. Kept so old-schema records keep working.
    { id: 'M-1', market: 'Music', mechanism: 'Monetization threshold', claim: 'Spotify: 1,000 trailing annual streams required for recorded royalty eligibility.', date: 'Observed · Apr 2024', direction: 'supports', state: 'VERIFIED', note: 'Does not establish anti-creator intent; does not affect publishing royalties.' },
    { id: 'M-2', market: 'Music', mechanism: 'Licensed-lane construction', claim: 'Spotify + major rights holders announced artist-first generative-AI collaboration under opt-in licensing structures.', date: 'Observed · Oct 2025', direction: 'supports', state: 'VERIFIED', note: 'Direct coordination inside music; not evidence of cross-market command.' },
    { id: 'M-3', market: 'Music', mechanism: 'Export restriction', claim: 'Udio downloads remained disabled during the UMG transition.', date: 'Confirmed · Feb 2026', direction: 'supports', state: 'VERIFIED', note: 'Strong creation-side pincer example; later reversals should be preserved separately.' },
    { id: 'M-4', market: 'Music', mechanism: 'Open technical counter', claim: 'Stable Audio 3.0 released open-weight models.', date: 'Observed · May 2026', direction: 'weakens', state: 'VERIFIED', note: 'Counterexample to a universal technical-closure claim.' },
    { id: 'M-5', market: 'Music', mechanism: 'Discovery restriction', claim: 'AI-persona profiles announced for default exclusion from recommendations.', date: 'Announced · Aug 2026', direction: 'supports', state: 'VERIFIED', note: 'Targets AI-persona identity rather than all AI-assisted music.' },
    { id: 'P-1', market: 'Publishing', mechanism: 'AI disclosure', claim: 'KDP requires disclosure of AI-generated text, images or translations; AI-assisted work is exempt.', date: 'Since · Sep 2023', direction: 'supports', state: 'VERIFIED', note: 'Disclosure is not itself a customer-facing ban.' },
    { id: 'P-2', market: 'Publishing', mechanism: 'Volume gate', claim: 'KDP current help limits title creation to 10 titles per book format each week.', date: 'Snapshot · Aug 2026', direction: 'supports', state: 'VERIFIED', note: 'Prototype record; confirm source/date whenever the live docket is updated.' },
    { id: 'P-3', market: 'Publishing', mechanism: 'Authorized AI expansion', claim: 'Audible and ACX expand AI narration / voice-replica use inside authorized and labeled channels.', date: 'Observed · 2025–2026', direction: 'weakens', state: 'VERIFIED', note: 'Counterexample to a simple anti-AI ratchet.' },
    { id: 'S-1', market: 'Scholarly', mechanism: 'Verification', claim: 'arXiv endorsement requirements increased friction for new or unaffiliated submitters.', date: 'Observed · 2025–2026', direction: 'supports', state: 'VERIFIED', note: 'Does not by itself establish generative AI as the cause.' },
    { id: 'S-2', market: 'Scholarly', mechanism: 'Human-basis policy', claim: 'Zenodo permits AI as a tool but rejects raw AI-only or bulk AI deposits without verifiable human research basis.', date: 'Observed · Apr 2026', direction: 'supports', state: 'VERIFIED', note: 'Tightening with permitted use, not a blanket ban.' },
    { id: 'C-1', market: 'Cross-cutting', mechanism: 'Provenance / transparency', claim: 'EU AI Act transparency obligations began applying to covered synthetic media/content.', date: 'Observed · Aug 2026', direction: 'supports', state: 'VERIFIED', note: 'Regulatory pressure; not evidence of private cross-market coordination.' },
    { id: 'C-2', market: 'Cross-cutting', mechanism: 'Acquisition / provenance litigation', claim: 'Sony Music Publishing and Warner Chappell sued Anthropic alleging unlawful acquisition of copyrighted works for Claude development.', date: 'Filed · Aug 28 2026', direction: 'supports', state: 'VERIFIED', note: 'Allegations are not a judgment; treat only as a post-freeze receipt.' }
  ],

  events: [
    // ================= LEGACY RECORDS RE-DERIVED AS EVENTS (adjudicated on main by Rob; legacy_ref keeps the lineage) =================
    { event_id: 'EVT-0001', kind: 'evidence', title: 'Spotify: 1,000-stream royalty eligibility threshold', entity_id: 'ENT-SPOTIFY', mechanism_id: 'MECH-MONETIZATION', market: 'Music', date: '2024-04-01', date_precision: 'month', posted_at: '2026-08-13', direction: 'supports', magnitude: '1,000 trailing annual streams', magnitude_method: 'stated policy threshold', previous_state: 'WATCH', new_state: 'POSTED', transition_reason: 'Adjudicated restriction evidence on the public ledger (M-1).', source_refs: ['SRC-SPOTIFY-ROYALTY-2023'], counterevidence_refs: [], claim_refs: ['CLM-HOSTED', 'CLM-NULL-VOLUME'], legacy_ref: 'M-1', proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Does not establish anti-creator intent. Also fully consistent with the null hypothesis (payout-fraud / de-minimis cost).' },
    { event_id: 'EVT-0002', kind: 'evidence', title: 'Spotify + majors: opt-in licensed generative-AI lane', entity_id: 'ENT-SPOTIFY', mechanism_id: 'MECH-LICENSING', market: 'Music', date: '2025-10-16', date_precision: 'month', posted_at: '2026-08-13', direction: 'supports', magnitude: 'structural', magnitude_method: 'qualitative', previous_state: 'WATCH', new_state: 'POSTED', transition_reason: 'Adjudicated (M-2).', source_refs: ['SRC-SPOTIFY-AI-20251016'], counterevidence_refs: [], claim_refs: ['CLM-HOSTED', 'CLM-CROSSMKT'], legacy_ref: 'M-2', proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Direct coordination INSIDE music. Not cross-market command.' },
    { event_id: 'EVT-0003', kind: 'evidence', title: 'Udio disables user downloads after UMG settlement / JV', entity_id: 'ENT-UDIO', mechanism_id: 'MECH-EXPORT', market: 'Music', date: '2025-10-29', date_precision: 'day', posted_at: '2026-08-13', direction: 'supports', magnitude: 'downloads disabled', magnitude_method: 'binary capability', previous_state: 'WATCH', new_state: 'POSTED', transition_reason: 'Adjudicated (M-3). Creation-side pincer: export closed as a condition of the licensed lane.', source_refs: ['SRC-ROUTENOTE-20251124', 'SRC-CHARTLEX-20260512'], counterevidence_refs: [], claim_refs: ['CLM-HOSTED', 'CLM-HOSTED-ASYMMETRY'], legacy_ref: 'M-3', counterpart: { entity: 'Universal Music Group (rights holder)', effect: 'gains licensed control of a generation lane', mechanism: 'MECH-LICENSING', ledger_side: 'opening for rights holders / bite for users' }, proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED' },
    { event_id: 'EVT-0004', kind: 'transition', title: 'Udio 48-hour download window (RELEASE)', entity_id: 'ENT-UDIO', mechanism_id: 'MECH-EXPORT', market: 'Music', date: '2025-11-01', date_precision: 'unknown-within-Nov-2025', posted_at: '2026-09-05', direction: 'weakens', magnitude: '48 hours', magnitude_method: 'stated duration', previous_state: 'POSTED', new_state: 'AR', transition_reason: 'A release occurred. Release alone = AR. Durability not shown. This is the first complete BITE→RELEASE→BITE case in the corpus and it PRE-DATES the freeze; it calibrates the machine, it does not score PRED-002.', source_refs: ['SRC-ROUTENOTE-20251124', 'SRC-BILLBOARD-UDIO-48H'], counterevidence_refs: [], claim_refs: ['CLM-HOSTED'], prediction_refs: [], proposed_by: CLAUDE, audit_status: 'PROPOSED', note: 'Referenced in the M-3 note on main ("temporary reversals are retained separately") but never ledgered. Window dates [Unknown].' },
    { event_id: 'EVT-0005', kind: 'transition', title: 'Udio downloads disabled again after window (second BITE)', entity_id: 'ENT-UDIO', mechanism_id: 'MECH-EXPORT', market: 'Music', date: '2025-11-03', date_precision: 'unknown-within-Nov-2025', posted_at: '2026-09-05', direction: 'supports', magnitude: 'downloads disabled (persisting through May 2026 staged rollout)', magnitude_method: 'binary capability', previous_state: 'AR', new_state: 'POSTED', transition_reason: 'Release lasted 48 hours; export remains closed per 2025-11-24 and 2026-05-12 sources. AR → POSTED: the opening was not durable.', source_refs: ['SRC-ROUTENOTE-20251124', 'SRC-CHARTLEX-20260512'], counterevidence_refs: [], claim_refs: ['CLM-HOSTED', 'CLM-CADENCE-RECUR'], parent_event_id: 'EVT-0004', proposed_by: CLAUDE, audit_status: 'PROPOSED' },
    { event_id: 'EVT-0006', kind: 'evidence', title: 'arXiv Mathematics: endorsement policy tightened', entity_id: 'ENT-ARXIV', mechanism_id: 'MECH-IDENTITY', market: 'Scholarly', date: '2025-12-10', date_precision: 'day', posted_at: '2026-09-05', direction: 'supports', magnitude: 'endorsement gate (Math)', magnitude_method: 'policy scope', source_refs: ['SRC-ARXIV-20251210'], counterevidence_refs: [], claim_refs: ['CLM-CROSSMKT', 'CLM-NULL-VOLUME'], proposed_by: CLAUDE, audit_status: 'PROPOSED', note: 'Primary date recovered this seat. Precedes and is extended by EVT-0007.' },
    { event_id: 'EVT-0007', kind: 'evidence', title: 'arXiv: institutional email no longer sufficient for endorsement (all categories)', entity_id: 'ENT-ARXIV', mechanism_id: 'MECH-IDENTITY', market: 'Scholarly', date: '2026-01-21', date_precision: 'day', posted_at: '2026-08-13', direction: 'supports', magnitude: 'endorsement gate (all categories)', magnitude_method: 'policy scope', previous_state: 'WATCH', new_state: 'POSTED', transition_reason: 'Adjudicated (S-1).', source_refs: ['SRC-ARXIV-20260121'], counterevidence_refs: [], claim_refs: ['CLM-CROSSMKT', 'CLM-NULL-VOLUME'], legacy_ref: 'S-1', parent_event_id: 'EVT-0006', proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'arXiv states the rationale as "non-scientific submissions", not AI. The ledger correctly declines to attribute cause.' },
    { event_id: 'EVT-0008', kind: 'evidence', title: 'Zenodo: human research basis required; raw/bulk AI deposits rejected', entity_id: 'ENT-ZENODO', mechanism_id: 'MECH-PUBLICATION', market: 'Scholarly', date: '2026-04-01', date_precision: 'month', posted_at: '2026-08-13', direction: 'supports', magnitude: 'human basis required', magnitude_method: 'policy scope', previous_state: 'WATCH', new_state: 'POSTED', transition_reason: 'Adjudicated (S-2).', source_refs: ['SRC-ZENODO-POLICY'], counterevidence_refs: [], claim_refs: ['CLM-CROSSMKT', 'CLM-AUTHORSHIP', 'CLM-NULL-VOLUME'], legacy_ref: 'S-2', proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Tightening with permitted use, not a blanket ban.' },
    { event_id: 'EVT-0009', kind: 'transition', title: 'Stable Audio 3.0 released with open weights (OPENING)', entity_id: 'ENT-STABILITY', mechanism_id: 'MECH-DISTRIBUTION', market: 'Music', date: '2026-05-26', date_precision: 'day', posted_at: '2026-08-13', direction: 'weakens', magnitude: 'open weights', magnitude_method: 'binary capability', previous_state: 'WATCH', new_state: 'AR', transition_reason: 'Adjudicated as counter-evidence (M-4): kills the universal technical-closure parent. Under AR-AP-v2 an opening enters as AR until durability is shown.', source_refs: ['SRC-MARKTECHPOST-20260526'], counterevidence_refs: [], claim_refs: ['CLM-TECHCLOSURE', 'CLM-HOSTED-ASYMMETRY'], prediction_refs: ['PRED-TECHCLOSURE'], legacy_ref: 'M-4', proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Note wording on main: "Kills universal technical-closure parent claim." G3 softened it; see EVT-0037 (lineage).' },
    { event_id: 'EVT-0010', kind: 'transition', title: 'Stable Audio 3.0 open weights — AP candidate (durability)', entity_id: 'ENT-STABILITY', mechanism_id: 'MECH-DISTRIBUTION', market: 'Music', date: '2026-09-05', date_precision: 'day', posted_at: '2026-09-05', direction: 'weakens', magnitude: '≈3.4 months open', magnitude_method: 'elapsed time since release', previous_state: 'AR', new_state: 'AP', transition_reason: 'Weights remain publicly available ~3.4 months after release with no withdrawal observed. Proposing AP; Rob decides whether 3.4 months is "durable".', durability_evidence: 'No retraction observed 2026-05-26 → 2026-09-05 [Claude search 2026-09-05]. Weak: no primary Stability post captured.', source_refs: ['SRC-MARKTECHPOST-20260526'], counterevidence_refs: [], claim_refs: ['CLM-HOSTED-ASYMMETRY'], proposed_by: CLAUDE, audit_status: 'PROPOSED' },
    { event_id: 'EVT-0011', kind: 'evidence', title: 'KDP requires disclosure of AI-generated content; AI-assisted exempt', entity_id: 'ENT-KDP', mechanism_id: 'MECH-DISCLOSURE', market: 'Publishing', date: '2023-09-01', date_precision: 'month', posted_at: '2026-08-13', direction: 'supports', magnitude: 'disclosure gate', magnitude_method: 'policy scope', previous_state: 'WATCH', new_state: 'POSTED', transition_reason: 'Adjudicated (P-1).', source_refs: ['SRC-KDP-AI-DISCLOSURE'], counterevidence_refs: [], claim_refs: ['CLM-AUTHORSHIP', 'CLM-CROSSMKT'], legacy_ref: 'P-1', proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Disclosure is not a customer-facing ban.' },
    { event_id: 'EVT-0012', kind: 'evidence', title: 'KDP title-creation limit: 10 per book format per week (replaces 3/day)', entity_id: 'ENT-KDP', mechanism_id: 'MECH-VOLUME', market: 'Publishing', date: '2025-11-01', date_precision: 'quarter [Estimate: "late 2025" per secondary]', posted_at: '2026-08-13', direction: 'supports', magnitude: '10/week/format (30/week total)', magnitude_method: 'stated policy threshold', source_refs: ['SRC-AUTHORCLIMB-KDP', 'SRC-KDP-HELP-G201857950'], counterevidence_refs: [], claim_refs: ['CLM-AUTHORSHIP', 'CLM-NULL-VOLUME'], legacy_ref: 'P-2', proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Primary snapshot with retrieval date still pending; weight currently carried by a secondary source.' },
    { event_id: 'EVT-0013', kind: 'transition', title: 'Audible / ACX expand AI narration and Voice Replica inside authorized channels (OPENING)', entity_id: 'ENT-ACX', mechanism_id: 'MECH-LICENSING', market: 'Publishing', date: '2025-06-01', date_precision: 'year-range 2025–2026', posted_at: '2026-08-13', direction: 'weakens', magnitude: 'authorized lane', magnitude_method: 'qualitative', previous_state: 'WATCH', new_state: 'AR', transition_reason: 'Adjudicated as counter-evidence (P-3). Governance expanded AI use inside an authorized, labeled channel.', source_refs: ['SRC-ACX-AI-NARRATION'], counterevidence_refs: [], claim_refs: ['CLM-AUTHORSHIP', 'CLM-HOSTED-ASYMMETRY'], legacy_ref: 'P-3', proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Opening inside a licensed lane is simultaneously evidence FOR the governed-lane pattern. Double-sided by nature; kept as counter per main.' },
    { event_id: 'EVT-0014', kind: 'transition', title: 'ACX authorized AI narration — AP candidate', entity_id: 'ENT-ACX', mechanism_id: 'MECH-LICENSING', market: 'Publishing', date: '2026-09-05', date_precision: 'day', posted_at: '2026-09-05', direction: 'weakens', magnitude: '>12 months', magnitude_method: 'elapsed time', previous_state: 'AR', new_state: 'AP', transition_reason: 'Program has persisted across 2025–2026 per main. Proposing AP.', durability_evidence: 'Persistence across 2025–2026 per the public ledger; no primary re-fetch this seat.', source_refs: ['SRC-ACX-AI-NARRATION'], counterevidence_refs: [], claim_refs: ['CLM-HOSTED-ASYMMETRY'], proposed_by: CLAUDE, audit_status: 'PROPOSED' },
    { event_id: 'EVT-0015', kind: 'transition', title: 'Diamond Open Access journals — durable no-APC lane (AP candidate)', entity_id: 'ENT-DIAMONDOA', mechanism_id: 'MECH-PUBLICATION', market: 'Scholarly', date: '2026-08-13', date_precision: 'as-of', posted_at: '2026-09-05', direction: 'weakens', magnitude: 'large journal population, no APC', magnitude_method: 'qualitative per main counter-evidence section', previous_state: 'WATCH', new_state: 'AP', transition_reason: 'Main lists Diamond OA as strong counterevidence to universal scholarly closure. It is durable by any standard (years). Entering directly as AP candidate — the A/P book must not be born empty.', durability_evidence: 'Multi-year persistence; DOAJ population. Not fetched this seat — LOW until a primary count is captured.', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], counterevidence_refs: [], claim_refs: ['CLM-CROSSMKT', 'CLM-HOSTED-ASYMMETRY'], proposed_by: CLAUDE, audit_status: 'PROPOSED' },
    { event_id: 'EVT-0016', kind: 'evidence', title: 'EU AI Act Art. 50 transparency obligations apply', entity_id: 'ENT-EUAIACT', mechanism_id: 'MECH-PROVENANCE', market: 'Cross-cutting', date: '2026-08-02', date_precision: 'day', posted_at: '2026-08-13', direction: 'supports', magnitude: 'transparency gate', magnitude_method: 'statutory scope', previous_state: 'WATCH', new_state: 'POSTED', transition_reason: 'Adjudicated (C-1).', source_refs: ['SRC-EUAIACT-ART50'], counterevidence_refs: [], claim_refs: ['CLM-CROSSMKT'], legacy_ref: 'C-1', causal_link: 'regulatory-common-cause', proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'ROOT of a regulatory common cause. Any downstream EU-driven disclosure record must link here or provenance will be triple-counted.' },
    { event_id: 'EVT-0017', kind: 'observation', title: 'Suno announces download limits (effective 2026-09-03)', entity_id: 'ENT-SUNO', mechanism_id: 'MECH-EXPORT', market: 'Music', date: '2026-08-10', date_precision: 'day', posted_at: '2026-09-05', direction: 'supports', magnitude: 'announced: Free 7 lifetime · Pro 20/mo · Premier 60/mo · Studio unlimited · retroactive · paid overage', magnitude_method: 'stated policy thresholds', source_refs: ['SRC-SUNO-TOS-20260810'], counterevidence_refs: [], claim_refs: ['CLM-HOSTED', 'CLM-CADENCE-RECUR'], proposed_by: CLAUDE, audit_status: 'PROPOSED', note: 'Announcement, pre-effect. Counter-note preserved: "Songs downloaded from Suno on paid plans remain yours." Ownership is not removed; export is metered.' },
    { event_id: 'EVT-0018', kind: 'transition', title: 'Suno download limits take effect; export metered and monetized', entity_id: 'ENT-SUNO', mechanism_id: 'MECH-EXPORT', market: 'Music', date: '2026-09-03', date_precision: 'day', posted_at: '2026-09-05', direction: 'supports', magnitude: 'Free 7 lifetime · Pro 20/mo · Premier 60/mo · applies to pre-existing songs', magnitude_method: 'stated policy thresholds', previous_state: 'WATCH', new_state: 'POSTED', transition_reason: 'Post-freeze bite on the export lane. Replicates the Udio export pattern (EVT-0003) through a DIFFERENT causal path: Udio was settlement-driven; Suno is ToS/business-driven. Counts to MECH-EXPORT confidence, not to Udio.', source_refs: ['SRC-SUNO-TOS-20260810'], counterevidence_refs: [], claim_refs: ['CLM-HOSTED', 'CLM-CADENCE-RECUR', 'CLM-HOSTED-ASYMMETRY'], prediction_refs: [], replication_of: 'EVT-0003', causal_link: 'independent-adoption', causal_link_confidence: '[Inference] — no evidence of copied policy or shared cause; different trigger', parent_event_id: 'EVT-0017', counterpart: { entity: 'Suno users with pre-existing libraries; portability tools (demand created)', effect: 'lose free export of existing work; alternative-channel demand appears', mechanism: 'MECH-METERING', ledger_side: 'bite for users; opening for substitutes' }, proposed_by: CLAUDE, audit_status: 'PROPOSED', note: 'Second mechanism on same event: MECH-METERING / MECH-MONETIZATION (paid overage). Recorded on the export lane; matrix shows metering via counterpart.' },
    { event_id: 'EVT-0019', kind: 'evidence', title: 'Spotify announces AI Persona label; default exclusion from recommendations (rollout mid-Sept 2026)', entity_id: 'ENT-SPOTIFY', mechanism_id: 'MECH-IDENTITY', market: 'Music', date: '2026-08-11', date_precision: 'day', posted_at: '2026-08-13', direction: 'supports', magnitude: 'default discovery exclusion (announced)', magnitude_method: 'stated policy', source_refs: ['SRC-SPOT-NEWSROOM-20260811', 'SRC-TC-20260811'], counterevidence_refs: [], claim_refs: ['CLM-HOSTED', 'CLM-DISCOVERYMODE', 'CLM-NULL-VOLUME'], legacy_ref: 'M-5', proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'ANNOUNCED, NOT IN FORCE as of 2026-09-05. Lane stays WATCH until observed after rollout. Recorded on the IDENTITY lane because determination is by identity review, with DISCOVERY as the effect. Opt-in via follow preserved as a counter-detail.' },
    { event_id: 'EVT-0020', kind: 'correction', title: 'CORRECTION: "Likely AI Persona" wording in M-5 is unsourced', entity_id: 'ENT-SPOTIFY', mechanism_id: 'MECH-IDENTITY', market: 'Music', date: '2026-09-05', date_precision: 'day', posted_at: '2026-09-05', parent_event_id: 'EVT-0019', source_refs: ['SRC-SPOT-NEWSROOM-20260811', 'SRC-TC-20260811'], counterevidence_refs: [], claim_refs: [], proposed_by: CLAUDE, audit_status: 'PROPOSED', note: 'main / G2a / G2b say "AI Persona / Likely AI Persona". Neither Spotify newsroom nor TechCrunch contains "Likely AI Persona". G3 dropped it silently. Origin [Unknown]. This correction does not delete EVT-0019; it annotates it. Rob to adjudicate whether the phrase has a source.' },
    { event_id: 'EVT-0021', kind: 'prediction-freeze', title: 'Prediction freeze 2026-08-13 (AI-Music Pincer)', entity_id: null, mechanism_id: null, market: 'Cross-cutting', date: '2026-08-13', date_precision: 'day', posted_at: '2026-08-13', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], prediction_refs: ['PRED-001', 'PRED-003', 'PRED-CADENCE-ORIG', 'PRED-TECHCLOSURE'], claim_refs: [], proposed_by: ROB, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Frozen text: "The gates will not close all at once. They will remain open just long enough to teach the crowd the road. Then the tolls will rise, the keys will change hands, and permission will masquerade as progress." Rhetoric; the scoreable content is in the prediction instruments.' },
    { event_id: 'EVT-0022', kind: 'evidence', title: 'Sony Music Publishing + Warner Chappell v. Anthropic filed', entity_id: 'ENT-ANTHROPIC', mechanism_id: 'MECH-PROVENANCE', market: 'Cross-cutting', date: '2026-08-28', date_precision: 'day', posted_at: '2026-08-30', direction: 'supports', magnitude: 'post-freeze receipt (allegation)', magnitude_method: 'qualitative', previous_state: 'WATCH', new_state: 'POSTED', transition_reason: 'Adjudicated (C-2) as consistent with an acquisition/provenance/licensing gate — not proof of the thesis.', source_refs: ['SRC-COURT-SONY-WARNER-V-ANTHROPIC', 'SRC-MBW-20260828', 'SRC-TC-20260829'], counterevidence_refs: [], claim_refs: ['CLM-HOSTED'], legacy_ref: 'C-2', counterpart: { entity: 'Sony Music Publishing; Warner Chappell', effect: 'assert licensing/provenance control over training corpus acquisition', mechanism: 'MECH-LICENSING', ledger_side: 'pressure applied by rights holders' }, proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Filed 15 days after freeze. Allegations are not a judgment.' },
    { event_id: 'EVT-0023', kind: 'prediction-freeze', title: 'Protocol freeze 2026-08-30: failure/resurrection rules; PRED-002 frozen', entity_id: null, mechanism_id: null, market: 'Cross-cutting', date: '2026-08-30', date_precision: 'day', posted_at: '2026-08-30', source_refs: ['SRC-PROTOCOL-20260830'], prediction_refs: ['PRED-002'], claim_refs: ['CLM-CADENCE-RECUR', 'CLM-HOSTED-ASYMMETRY'], proposed_by: ROB_PROTO, adjudicated_by: ROB_PROTO, audit_status: 'POSTED', note: 'Two-receipt rule frozen prospectively. "No later event may alter the text or date of an earlier frozen prediction."' },
    { event_id: 'EVT-0024', kind: 'prediction-resolution', title: 'PRED-CADENCE-ORIG (six-month interval) — FALSIFIED → GRAVEYARD', entity_id: null, mechanism_id: null, market: 'Cross-cutting', date: '2026-08-30', date_precision: 'day', posted_at: '2026-08-30', resolution: 'FALSIFIED', source_refs: ['SRC-PROTOCOL-20260830', 'SRC-MAIN-PREVIEW-7d3a6d5'], prediction_refs: ['PRED-CADENCE-ORIG'], claim_refs: ['CLM-CADENCE-INTERVAL'], current_confidence: null, proposed_by: ROB_PROTO, adjudicated_by: ROB_PROTO, audit_status: 'POSTED', note: 'Main: "Original interval estimate: roughly six months — failed." Descendant CLM-CADENCE-RECUR survives (and, as written, cannot miss — audit A-5).' },
    { event_id: 'EVT-0025', kind: 'prediction-resolution', title: 'PRED-TECHCLOSURE (universal technical closure) — FALSIFIED / ASH → descendant', entity_id: null, mechanism_id: null, market: 'Music', date: '2026-08-30', date_precision: 'day', posted_at: '2026-08-30', resolution: 'FALSIFIED', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5', 'SRC-MARKTECHPOST-20260526'], prediction_refs: ['PRED-TECHCLOSURE'], claim_refs: ['CLM-TECHCLOSURE'], proposed_by: ROB, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Main: "universal technical closure remains ash." Descendant: hosted-access asymmetry (CLM-HOSTED-ASYMMETRY).' },
    { event_id: 'EVT-0026', kind: 'adjudication', title: 'CLM-HOSTED — HOLDS (INSTINCT SHOWN — STRONG)', entity_id: null, mechanism_id: null, market: 'Cross-cutting', date: '2026-08-30', date_precision: 'approx [Inference: receipts section cites the 08-30 protocol]', posted_at: '2026-08-30', claim_status: 'SURVIVING', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], claim_refs: ['CLM-HOSTED'], proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Main receipt: "Udio/Suno/Spotify/publishing controls and the Sony/Warner v. Anthropic acquisition/provenance pressure are consistent with a more governed convenient lane."' },
    { event_id: 'EVT-0027', kind: 'adjudication', title: 'CLM-CROSSMKT — HOLDS — NARROWED', entity_id: null, mechanism_id: null, market: 'Cross-cutting', date: '2026-08-30', date_precision: 'approx', posted_at: '2026-08-30', claim_status: 'SURVIVING', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], claim_refs: ['CLM-CROSSMKT'], proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: '"Similar primitives recur; unified secret coordination is not established."' },
    { event_id: 'EVT-0028', kind: 'adjudication', title: 'CLM-AUTHORSHIP — INSTINCT SHOWN — ALREADY UNDERWAY', entity_id: null, mechanism_id: null, market: 'Publishing', date: '2026-08-30', date_precision: 'approx', posted_at: '2026-08-30', claim_status: 'SURVIVING', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], claim_refs: ['CLM-AUTHORSHIP'], proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'This receipt was DROPPED from gate-closing-data.js (G3). Restored here from main.' },
    { event_id: 'EVT-0029', kind: 'adjudication', title: 'CLM-COORDINATION — NOT ESTABLISHED', entity_id: null, mechanism_id: null, market: 'Cross-cutting', date: '2026-08-30', date_precision: 'approx', posted_at: '2026-08-30', claim_status: 'NOT ESTABLISHED', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], claim_refs: ['CLM-COORDINATION'], proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: '"Direct coordination exists inside music. No direct evidence here establishes a single command structure spanning music, publishing and scholarly deposit systems." DROPPED from G3; restored.' },
    { event_id: 'EVT-0030', kind: 'adjudication', title: 'CLM-CADENCE-INTERVAL — FALSIFIED (REVISED / REOPENED as CLM-CADENCE-RECUR)', entity_id: null, mechanism_id: null, market: 'Cross-cutting', date: '2026-08-30', date_precision: 'day', posted_at: '2026-08-30', claim_status: 'FALSIFIED', source_refs: ['SRC-PROTOCOL-20260830'], claim_refs: ['CLM-CADENCE-INTERVAL'], proposed_by: ROB_PROTO, adjudicated_by: ROB_PROTO, audit_status: 'POSTED', note: 'DROPPED from G3; restored.' },
    { event_id: 'EVT-0031', kind: 'adjudication', title: 'CLM-TECHCLOSURE — ASH → DESCENDANT', entity_id: null, mechanism_id: null, market: 'Music', date: '2026-08-30', date_precision: 'day', posted_at: '2026-08-30', claim_status: 'FALSIFIED', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], claim_refs: ['CLM-TECHCLOSURE'], proposed_by: ROB, adjudicated_by: ROB, audit_status: 'POSTED', note: 'DROPPED from G3; restored.' },
    { event_id: 'EVT-0032', kind: 'adjudication', title: 'CLM-CADENCE-RECUR — descendant, REVISED, live', entity_id: null, mechanism_id: null, market: 'Cross-cutting', date: '2026-08-30', date_precision: 'day', posted_at: '2026-08-30', claim_status: 'UNRESOLVED', source_refs: ['SRC-PROTOCOL-20260830'], claim_refs: ['CLM-CADENCE-RECUR'], proposed_by: ROB_PROTO, adjudicated_by: ROB_PROTO, audit_status: 'POSTED', note: 'Surviving cadence claim has no stated window. Cannot miss as written.' },
    { event_id: 'EVT-0033', kind: 'adjudication', title: 'CLM-HOSTED-ASYMMETRY — descendant, live', entity_id: null, mechanism_id: null, market: 'Music', date: '2026-08-30', date_precision: 'day', posted_at: '2026-08-30', claim_status: 'SURVIVING', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], claim_refs: ['CLM-HOSTED-ASYMMETRY'], proposed_by: ROB, adjudicated_by: ROB, audit_status: 'POSTED' },
    { event_id: 'EVT-0034', kind: 'adjudication', title: 'CLM-KDP-DISCOVERY / CLM-DISCOVERYMODE — OPEN / VULNERABLE, not publishable as fact', entity_id: null, mechanism_id: null, market: 'Publishing', date: '2026-08-30', date_precision: 'approx', posted_at: '2026-08-30', claim_status: 'UNRESOLVED', source_refs: ['SRC-MAIN-PREVIEW-7d3a6d5'], claim_refs: ['CLM-KDP-DISCOVERY', 'CLM-DISCOVERYMODE'], proposed_by: LEGACY, adjudicated_by: ROB, audit_status: 'POSTED', note: 'G2a posted "KDP discoverability descendant" as an ACCOUNTS RECEIVABLE receipt. On main it is a vulnerable claim, not a receipt. The G2a receipt has no upstream source.' },
    { event_id: 'EVT-0035', kind: 'evidence', title: 'Suno / MusicFlow ownership hunch frozen (INTERNAL)', visibility: 'internal', entity_id: 'ENT-MUSICFLOW', mechanism_id: 'MECH-EXPORT', market: 'Music', date: '2026-09-03', date_precision: 'day', posted_at: '2026-09-03', direction: 'open', magnitude: 'hunch — unverified', magnitude_method: 'n/a', source_refs: ['SRC-HUNCH-20260903'], counterevidence_refs: [], claim_refs: [], prediction_refs: ['PRED-005-HUNCH'], proposed_by: ROB, adjudicated_by: ROB, audit_status: 'POSTED', note: 'Repository evidence only. Not approved for the public page. Hidden unless INTERNAL view is enabled.' },
    { event_id: 'EVT-0036', kind: 'counterpart', title: 'IngramSpark: upfront fee removed (opening) / backend fee added (bite) — double-entry pair', entity_id: 'ENT-INGRAM', mechanism_id: 'MECH-MONETIZATION', market: 'Publishing', date: '2026-08-24', date_precision: 'as-of status file [Unknown actual dates]', posted_at: '2026-09-05', direction: 'open', magnitude: 'mixed', magnitude_method: 'qualitative', source_refs: ['SRC-STATUS-MD-20260824'], counterevidence_refs: [], claim_refs: ['CLM-AUTHORSHIP'], counterpart: { entity: 'IngramSpark authors', effect: 'front-loaded cost removed; back-loaded cost added', mechanism: 'MECH-MONETIZATION', ledger_side: 'opening AND bite on the same entity' }, proposed_by: CLAUDE, audit_status: 'PROPOSED', note: 'Source is a derived repo status note (LOW). Needs primary IngramSpark pricing pages with dates before any state transition is proposed.' },
    { event_id: 'EVT-0037', kind: 'lineage', title: 'LINEAGE: gate-closing-data.js (2026-09-04) dropped 4 of 8 main receipts and softened two notes', entity_id: null, mechanism_id: null, market: 'Cross-cutting', date: '2026-09-04', date_precision: 'day', posted_at: '2026-09-05', source_refs: ['SRC-DATAJS-20260904', 'SRC-MAIN-PREVIEW-7d3a6d5'], claim_refs: [], proposed_by: CLAUDE, audit_status: 'PROPOSED', note: 'Dropped: Cadence REVISED; Technical closure ASH→DESCENDANT; Authorship gate; Unified coordination NOT ESTABLISHED. Softened: M-4 note ("Kills…" → "Counterexample…"); M-3 note. Restored above as EVT-0028…0032 with legacy_ref to main. G3 file itself is preserved verbatim in legacy_records.' },
    { event_id: 'EVT-0038', kind: 'lineage', title: 'LINEAGE: G2a terminal prototype posts three receipts with no upstream source', entity_id: null, mechanism_id: null, market: 'Cross-cutting', date: '2026-09-05', date_precision: 'day', posted_at: '2026-09-05', source_refs: ['SRC-G2A-TERMINAL'], claim_refs: [], proposed_by: CLAUDE, audit_status: 'PROPOSED', note: '"OPEN SOURCE WATCH — Hugging Face / open model governance", "HIGH SUPPORT — Plan-and-meter control plane", "ACCOUNTS RECEIVABLE — KDP discoverability descendant". Also: survival percentages (84/66/18/12/58/28) and status strip (4/4/5/2/1/3) are literals with no derivation. Not imported. Flagged.' }
  ]
};
