#!/usr/bin/env node
/* Replays tools/journal-source.js through the engine's own validators, one event at a time,
 * then writes ../gate-closing-journal.js with seq / prev_hash / content_hash filled in.
 * If the seed violates its own rules, sealing FAILS. The journal never self-certifies.
 */
const fs = require('fs'), path = require('path');
const E = require('../gate-closing-engine.js');
const src = require('./journal-source.js');

let journal = { ...src, predictions: [], events: [] };
const report = { predictions: [], events: [], warnings: [] };

// predictions: freeze the frozen ones (hash), keep drafts unhashed
for (const p of src.predictions) {
  if (p.frozen_at) { const r = E.freezePrediction(journal, p, { now: p.frozen_at }); journal = r.journal; report.predictions.push(`${p.prediction_id} frozen ${p.frozen_at} hash ${r.prediction.content_hash.slice(0, 12)}…`); }
  else { const v = E.validatePrediction(journal, p); if (!v.ok) throw new Error(p.prediction_id + ': ' + v.errors.join(' | ')); journal.predictions.push({ ...p, content_hash: null }); report.predictions.push(`${p.prediction_id} DRAFT (unfrozen, no hash)`); }
}
// events: replay with validation
for (const ev of src.events) {
  try {
    const r = E.appendEvent(journal, ev);
    journal = r.journal;
    report.events.push(`${ev.event_id} ok seq ${r.event.seq}` + (r.warnings.length ? '  WARN: ' + r.warnings.join('; ') : ''));
    r.warnings.forEach(w => report.warnings.push(ev.event_id + ': ' + w));
  } catch (e) { console.error('SEAL FAILED at ' + ev.event_id + '\n  ' + (e.errors || [e.message]).join('\n  ')); process.exit(1); }
}
const chain = E.verifyChain(journal);
if (!chain.ok) { console.error('CHAIN BROKEN', chain.problems); process.exit(1); }

const out = path.join(__dirname, '..', 'gate-closing-journal.js');
const header = `/* GATE CLOSING — SEALED EVIDENCE JOURNAL (gc-journal/1)
 * GENERATED by tools/seal-journal.js from tools/journal-source.js on ${new Date().toISOString()}
 * DO NOT EDIT BY HAND. Append to journal-source.js and re-seal. Hash chain: ${journal.events.length} events, head ${journal.events[journal.events.length - 1].content_hash}
 * Verify any event: sha256(canonical({prev: prev_hash, event: <event without content_hash/prev_hash>})) — see engine.eventHashInput.
 */
`;
fs.writeFileSync(out, header + 'window.GC_JOURNAL = ' + JSON.stringify(journal, null, 1) + ';\n');
fs.writeFileSync(path.join(__dirname, 'seal-report.txt'), ['PREDICTIONS', ...report.predictions, '', 'EVENTS', ...report.events, '', 'WARNINGS', ...report.warnings].join('\n') + '\n');
console.log(`sealed ${journal.events.length} events, ${journal.predictions.length} predictions → ${out}`);
console.log(`chain head ${journal.events[journal.events.length - 1].content_hash}`);
if (report.warnings.length) console.log('warnings:\n  ' + report.warnings.join('\n  '));
